# Generated by Django 5.2.1 on 2025-05-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_etiqueta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_palabra', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EsAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilo_esatributo', to='tecnicas.estilopalabra')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escala', models.CharField(max_length=255)),
                ('longitud', models.IntegerField()),
                ('etiquetas', models.ManyToManyField(to='tecnicas.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atributos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributo_listapalabras', to='tecnicas.esatributo')),
                ('id_palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_listapalabras', to='tecnicas.palabra')),
            ],
        ),
        migrations.CreateModel(
            name='SesionSensorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(verbose_name='date published')),
                ('activo', models.BooleanField(default=False)),
                ('creadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentador_sesion', to='tecnicas.presentador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=3)),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_sesion', to='tecnicas.sesionsensorial')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnica', models.CharField(max_length=255)),
                ('maximas_repeticiones', models.IntegerField(default=0)),
                ('repecion', models.IntegerField(default=0)),
                ('limite_catadores', models.IntegerField()),
                ('instrucciones', models.CharField(max_length=255)),
                ('id_estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilo_tecnica', to='tecnicas.estilopalabra')),
            ],
        ),
        migrations.AddField(
            model_name='sesionsensorial',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_tecnica', to='tecnicas.tecnica'),
        ),
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomre_vocabulario', models.CharField(max_length=255, unique=True)),
                ('palabras', models.ManyToManyField(to='tecnicas.palabra')),
            ],
        ),
        migrations.CreateModel(
            name='EsVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilo_esvacabulario', to='tecnicas.estilopalabra')),
                ('id_vocabulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario_esvocabulario', to='tecnicas.vocabulario')),
            ],
        ),
    ]
