# Generated by Django 5.2.1 on 2025-07-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapalabra',
            name='id_atributos',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='esvocabulario',
            name='id_estilo',
        ),
        migrations.RemoveField(
            model_name='tecnica',
            name='id_estilo',
        ),
        migrations.RemoveField(
            model_name='esvocabulario',
            name='id_vocabulario',
        ),
        migrations.RemoveField(
            model_name='listapalabra',
            name='id_palabra',
        ),
        migrations.RemoveField(
            model_name='vocabulario',
            name='palabras',
        ),
        migrations.RemoveField(
            model_name='sesionsensorial',
            name='creadoPor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_sesion',
        ),
        migrations.RemoveField(
            model_name='sesionsensorial',
            name='tecnica',
        ),
        migrations.DeleteModel(
            name='EsAtributo',
        ),
        migrations.DeleteModel(
            name='Escala',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='EstiloPalabra',
        ),
        migrations.DeleteModel(
            name='EsVocabulario',
        ),
        migrations.DeleteModel(
            name='ListaPalabra',
        ),
        migrations.DeleteModel(
            name='Palabra',
        ),
        migrations.DeleteModel(
            name='Vocabulario',
        ),
        migrations.DeleteModel(
            name='Presentador',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='SesionSensorial',
        ),
        migrations.DeleteModel(
            name='Tecnica',
        ),
    ]
