# Generated by Django 5.2.1 on 2025-07-15 16:58

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicas', '0002_remove_listapalabra_id_atributos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCatador', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_etiqueta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_palabra', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_repeticion', models.IntegerField(max_length=3)),
                ('id_catador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_catador', to='tecnicas.catador')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_producto', to='tecnicas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.IntegerField(max_length=3)),
                ('etiquetas', models.ManyToManyField(to='tecnicas.etiqueta')),
                ('id_tipo_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_tipo_escala', to='tecnicas.tipoescala')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_catador', to='tecnicas.catador')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_calificacion', to='tecnicas.calificacion')),
                ('id_palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_palabra', to='tecnicas.palabra')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(max_length=2)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_orden', to='tecnicas.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_producto', to='tecnicas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones_max', models.IntegerField(default=0)),
                ('repecion', models.IntegerField(default=0)),
                ('limite_catadores', models.IntegerField()),
                ('instrucciones', models.CharField(max_length=255)),
                ('id_estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilo_tecnica', to='tecnicas.estilopalabra')),
            ],
        ),
        migrations.CreateModel(
            name='SesionSensorial',
            fields=[
                ('codigo_sesion', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('nombre_sesion', models.CharField(max_length=255, null=True)),
                ('fechaCreacion', models.DateTimeField(verbose_name='date published')),
                ('activo', models.BooleanField(default=False)),
                ('creadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentador_sesion', to='tecnicas.presentador')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_tecnica', to='tecnicas.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='EsAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras', models.ManyToManyField(related_name='estilo_atributo_palabras', to='tecnicas.palabra')),
                ('id_tecnica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_esatributo', to='tecnicas.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaIntensidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_escala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_intensidad', to='tecnicas.escala')),
                ('id_tecnica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_intensidad', to='tecnicas.tecnica')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_intensidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_tecnica_intensidad', to='tecnicas.tecnicaintensidad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_intensidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_tecnica_intensidad', to='tecnicas.tecnicaintensidad'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_intensidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_tec_intensidad', to='tecnicas.tecnicaintensidad'),
        ),
        migrations.CreateModel(
            name='TipoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnica', models.CharField(max_length=255)),
                ('id_categoria_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tecnica_categoria_tecnica', to='tecnicas.categoriatecnica')),
            ],
        ),
        migrations.AddField(
            model_name='tecnica',
            name='tipo_tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_tipo_tecnica', to='tecnicas.tipotecnica'),
        ),
        migrations.CreateModel(
            name='ValorBooleano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField()),
                ('id_dato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dato_boolean', to='tecnicas.dato')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDecimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('id_dato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dato_decimal', to='tecnicas.dato')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomre_vocabulario', models.CharField(max_length=255, unique=True)),
                ('palabras', models.ManyToManyField(related_name='vovabulario_palabras', to='tecnicas.palabra')),
            ],
        ),
        migrations.CreateModel(
            name='EsVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tecnica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_esvacabulario', to='tecnicas.tecnica')),
                ('id_vocabulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario_esvocabulario', to='tecnicas.vocabulario')),
            ],
        ),
    ]
