# Generated by Django 5.2.1 on 2025-07-15 17:28

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='num_repeticion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='escala',
            name='longitud',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='esvocabulario',
            name='id_vocabulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario_esvocabulario', to='tecnicas.vocabulario', unique=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='posicion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presentador',
            name='nombre_usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipotecnica',
            name='nombre_tecnica',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
