# Generated by Django 5.2.1 on 2025-07-15 17:31

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0004_alter_calificacion_num_repeticion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esvocabulario',
            name='id_vocabulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario_esvocabulario', to='tecnicas.vocabulario'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
