# Generated by Django 5.2.1 on 2025-07-20 16:18

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0005_alter_esvocabulario_id_vocabulario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='id_calificacion',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='id_palabra',
        ),
        migrations.RemoveField(
            model_name='valorbooleano',
            name='id_dato',
        ),
        migrations.RemoveField(
            model_name='valordecimal',
            name='id_dato',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='id_catador',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='id_intensidad',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_intensidad',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='etiquetas',
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EtiquetasEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('id_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_etiqutas_escala', to='tecnicas.escala')),
                ('id_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_etiquetas_escala', to='tecnicas.etiqueta')),
            ],
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='ValorBooleano',
        ),
        migrations.DeleteModel(
            name='Dato',
        ),
        migrations.DeleteModel(
            name='ValorDecimal',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Posicion',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
