# Generated by Django 5.2.1 on 2025-07-20 16:19

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0006_remove_dato_id_calificacion_remove_dato_id_palabra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_repeticion', models.IntegerField()),
                ('id_catador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_catador', to='tecnicas.catador')),
                ('id_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_tecnica', to='tecnicas.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_calificacion', to='tecnicas.calificacion')),
                ('id_palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_palabra', to='tecnicas.palabra')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_catador', to='tecnicas.catador')),
                ('id_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_tecnica', to='tecnicas.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=3)),
                ('id_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_tecnica', to='tecnicas.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_orden', to='tecnicas.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_producto', to='tecnicas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_producto', to='tecnicas.producto'),
        ),
        migrations.CreateModel(
            name='ValorBooleano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BooleanField()),
                ('id_dato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dato_boolean', to='tecnicas.dato')),
            ],
        ),
        migrations.CreateModel(
            name='ValorDecimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('id_dato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dato_decimal', to='tecnicas.dato')),
            ],
        ),
    ]
