# Generated by Django 5.2.1 on 2025-07-22 20:59

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0007_alter_sesionsensorial_codigo_sesion_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='valor_etiqueta',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
