# Generated by Django 5.2.1 on 2025-08-01 21:27

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0008_alter_etiqueta_valor_etiqueta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_catador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_catador', to='tecnicas.catador'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
