# Generated by Django 5.2.1 on 2025-08-11 23:21

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0009_alter_orden_id_catador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='tecnica',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='escala_tecnica', to='tecnicas.tecnica'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TecnicaIntensidad',
        ),
    ]
