# Generated by Django 5.2.1 on 2025-09-10 00:04

import django.utils.timezone
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0013_alter_sesionsensorial_codigo_sesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
