# Generated by Django 5.2.1 on 2025-09-18 19:49

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0015_alter_sesionsensorial_codigo_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=True)),
                ('catador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catador_participacion', to='tecnicas.catador')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_participacion', to='tecnicas.tecnica')),
            ],
        ),
    ]
