# Generated by Django 5.2.1 on 2025-09-28 15:18

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0018_alter_sesionsensorial_codigo_sesion_participacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnica',
            old_name='repecion',
            new_name='repeticion',
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
