# Generated by Django 5.2.1 on 2025-10-18 23:34

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0019_rename_repecion_tecnica_repeticion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='catador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='catador',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='catador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='catador',
            name='usuarioCatador',
        ),
        migrations.RemoveField(
            model_name='presentador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='presentador',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='presentador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='presentador',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='catador',
            name='genero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='catador',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catador',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_catador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentador',
            name='telefono',
            field=models.BigIntegerField(default=555),
        ),
        migrations.AddField(
            model_name='presentador',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_presentador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catador',
            name='telefono',
            field=models.BigIntegerField(default=555),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
