# Generated by Django 5.2.1 on 2025-11-06 21:46

import django.utils.timezone
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0020_remove_catador_apellido_remove_catador_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulario',
            old_name='nomre_vocabulario',
            new_name='nombre_vocabulario',
        ),
        migrations.AddField(
            model_name='vocabulario',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
