# Generated by Django 5.2.1 on 2025-11-25 01:18

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0023_alter_sesionsensorial_codigo_sesion_listapalabras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catador_grupo_producto', to='tecnicas.catador')),
                ('palabras', models.ManyToManyField(related_name='grupo_producto', to='tecnicas.palabra')),
                ('productos', models.ManyToManyField(related_name='grupo_producto', to='tecnicas.producto')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnica_grupo_producto', to='tecnicas.tecnica')),
            ],
        ),
    ]
