# Generated by Django 5.2.1 on 2025-11-29 03:05

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0030_alter_sesionsensorial_codigo_sesion_tecnicamodalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='palabras',
            field=models.ManyToManyField(blank=True, related_name='calificacion_palabras', to='tecnicas.palabra'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DatoPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_punto', to='tecnicas.calificacion')),
            ],
        ),
    ]
