# Generated by Django 5.2.1 on 2026-01-22 19:34

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0031_calificacion_palabras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotecnica',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
