# Generated by Django 5.2.1 on 2026-01-30 17:50

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0033_participacion_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_tecnica', to='tecnicas.tecnica'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
