# Generated by Django 5.2.1 on 2026-02-02 18:43

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0034_alter_escala_tecnica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CalificacionEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicas.calificacion')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicas.escala')),
            ],
            options={
                'verbose_name': 'Calificación Escala',
                'verbose_name_plural': 'Calificaciones Escalas',
                'db_table': 'calificacion_escala',
                'unique_together': {('calificacion', 'escala')},
            },
        ),
    ]
