# Generated by Django 5.2.1 on 2026-02-04 18:07

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0036_alter_sesionsensorial_codigo_sesion_datohedonico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionescala',
            name='calificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_escala', to='tecnicas.calificacion'),
        ),
        migrations.AlterField(
            model_name='calificacionescala',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_escala', to='tecnicas.escala'),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
