# Generated by Django 5.2.1 on 2026-02-05 16:49

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0037_alter_calificacionescala_calificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datohedonico',
            old_name='id_calificacion',
            new_name='calificacion',
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
