# Generated by Django 5.2.1 on 2026-02-15 18:29
# Seeds for the application tecnicas

from django.db import migrations


def create_type_scales(apps, schema_editor):
    TipoEscala = apps.get_model('tecnicas', 'TipoEscala')

    create_type_scales = [
        {'nombre_escala': 'ideal'},
        {'nombre_escala': 'hedonica'},
        {'nombre_escala': 'continua'},
        {'nombre_escala': 'estructurada'},
    ]

    for scale in create_type_scales:
        TipoEscala.objects.get_or_create(**scale)


def create_tags(apps, schema_editor):
    Etiqueta = apps.get_model('tecnicas', 'Etiqueta')

    create_tags_intensity = [
        {'valor_etiqueta': 'percepcion nula'},
        {'valor_etiqueta': 'ligera percepcion'},
        {'valor_etiqueta': 'poca percepcion'},
        {'valor_etiqueta': 'percepcion moderada'},
        {'valor_etiqueta': 'se puede percibir'},
        {'valor_etiqueta': 'buena percepcion'},
        {'valor_etiqueta': 'percepcion intensa'},
        {'valor_etiqueta': 'percepcion muy intensa'},
        {'valor_etiqueta': 'percepcion total'},
    ]

    for tag in create_tags_intensity:
        Etiqueta.objects.get_or_create(**tag)

    create_tags_hedonic = [
        {'valor_etiqueta': 'me gusta muchísimo'},
        {'valor_etiqueta': 'me gusta mucho'},
        {'valor_etiqueta': 'me gusta moderadamente'},
        {'valor_etiqueta': 'me gusta un poco'},
        {'valor_etiqueta': 'ni me gusta ni me disgusta'},
        {'valor_etiqueta': 'me disgusta un poco'},
        {'valor_etiqueta': 'me disgusta moderadamente'},
        {'valor_etiqueta': 'me disgusta mucho'},
        {'valor_etiqueta': 'me disgusta muchísimo'},
    ]

    for tag in create_tags_hedonic:
        Etiqueta.objects.get_or_create(**tag)


def create_modes(apps, schema_editor):
    Modalidad = apps.get_model('tecnicas', 'Modalidad')

    create_modes = [
        {'nombre': 'posicionamiento'},
        {'nombre': 'perfil ultra flash'},
        {'nombre': 'sorting'},
    ]

    for mode in create_modes:
        Modalidad.objects.get_or_create(**mode)


def create_categories_techiques(apps, schema_editor):
    CategoriaTecnica = apps.get_model('tecnicas', 'CategoriaTecnica')

    create_categories = [
        {'nombre_categoria': 'rápida'},
        {'nombre_categoria': 'convencional'},
    ]

    for category in create_categories:
        CategoriaTecnica.objects.get_or_create(**category)


def create_type_techniques(apps, schema_editor):
    TipoTecnica = apps.get_model('tecnicas', 'TipoTecnica')
    CategoriaTecnica = apps.get_model('tecnicas', 'CategoriaTecnica')

    convencional_type_techniques = [
        {
            'nombre_tecnica': 'escalas',
            'descripcion': 'Escalas de intensidad',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='convencional')
        },
        {
            'nombre_tecnica': 'perfil_ideal',
            'descripcion': 'Perfil ideal',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='convencional')
        },
    ]

    for type in convencional_type_techniques:
        TipoTecnica.objects.get_or_create(**type)

    fast_type_techniques = [
        {
            'nombre_tecnica': 'rata',
            'descripcion': 'Rate-all-that-apply (RATA)',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='rápida')
        },
        {
            'nombre_tecnica': 'cata',
            'descripcion': 'Check-all-that-apply (CATA)',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='rápida')
        },
        {
            'nombre_tecnica': 'perfil flash',
            'descripcion': 'Perfil Flash',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='rápida')
        },
        {
            'nombre_tecnica': 'sort',
            'descripcion': 'Categorización (Sorting task)',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='rápida')
        },
        {
            'nombre_tecnica': 'napping',
            'descripcion': 'Mantel (Napping)',
            'id_categoria_tecnica': CategoriaTecnica.objects.get(nombre_categoria='rápida')
        },
    ]

    for type in fast_type_techniques:
        TipoTecnica.objects.get_or_create(**type)


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0038_rename_id_calificacion_datohedonico_calificacion_and_more'),
    ]

    operations = [
        migrations.RunPython(create_type_scales),
        migrations.RunPython(create_tags),
        migrations.RunPython(create_modes),
        migrations.RunPython(create_categories_techiques),
        migrations.RunPython(create_type_techniques),
    ]
