# Generated by Django 5.2.1 on 2026-02-15 21:21

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0039_auto_20260215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulario',
            name='descripcion',
            field=models.CharField(default='Vocabulario sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='sesionsensorial',
            name='codigo_sesion',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
