# Generated by Django 5.2.1 on 2026-02-15 21:46
# Created vocabularies for emotions and memories

from django.db import migrations


def create_words_emotions_memories(apps, schema_editor):
    Palabra = apps.get_model('tecnicas', 'Palabra')
    Vocabulario = apps.get_model('tecnicas', 'Vocabulario')

    # Vocabularies emotions
    ## #####################
    esSense25_emotions = ["jubiloso", "amoroso", "gentil", "nostalgico", "complacido", "satisfecho", "seguro", "docil", "comprensivo", "calido", "activo", "aventuroso",
                          "calmado", "entusiasta", "liberado", "bien", "de_buen_caracter", "feliz", "interesado", "salvaje", "preocupado", "agresivo", "aburrido", "disgustado", "culpable"]

    # All emotions
    words_emotions = {}
    esSense25_emotions_vocabulario, created_esSense25 = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Emociones EsSense25",
        descripcion="Vocabulario de emociones por EsSense25"
    )
    for word in esSense25_emotions:
        new_word, created = Palabra.objects.get_or_create(nombre_palabra=word)
        words_emotions[new_word.nombre_palabra] = new_word
        esSense25_emotions_vocabulario.palabras.add(new_word)

    # Reduced emotions by APJ
    apj_emotions = ["satisfecho", "docil", "feliz",
                    "interesado", "aburrido", "disgustado", "culpable"]
    apj_emotions_vocabulario, created_apj_emotions = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Emociones reducidas por APJ", descripcion="Lista reducida de emociones a partir de EsSense25 por APJ segun 'USO DE TECNICAS MULTICRITERIO PARA LA OBTENCION DE UNA LISTA REDUCIDA DE EMOCIONES Y RECUERDOS PARA CONSUMIDORES DE CAFES ARTESANALES'")
    for word in apj_emotions:
        new_word = words_emotions[word]
        apj_emotions_vocabulario.palabras.add(new_word)

    # Reduced emotions by Toposis
    toposis_emotions = ["bien", "de_buen_caracter", "disgustado", "culpable"]
    toposis_emotions_vocabylario, created_toposis_emotions = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Emociones reducidas por Toposis", descripcion="Lista reducida de emociones a partir de EsSense25 por Toposis segun 'USO DE TECNICAS MULTICRITERIO PARA LA OBTENCION DE UNA LISTA REDUCIDA DE EMOCIONES Y RECUERDOS PARA CONSUMIDORES DE CAFES ARTESANALES'")
    for word in toposis_emotions:
        new_word = words_emotions[word]
        toposis_emotions_vocabylario.palabras.add(new_word)

    # Vocabularies memories
    ## #####################
    menVOC_memories = ["comida_artesanal", "fiesta_familia", "lugar_de_nacimiento", "infancia", "amistad", "deporte", "vida", "obsequio", "primavera", "verano", "otoño", "invierno",
                       "clima_lluvioso", "clima_frío", "clima_caluroso", "clima_templado", "enfermedad", "dolor", "herir", "obesidad", "hedor", "adiccion", "pobreza", "muerte", "conflictos_personales", "accidente"]

    # All memories
    words_memories = {}
    menVOC_memories_vocabulario, created_menVOC_memories = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Memorias MemVOC", descripcion="Vocabulario de memorias o recuerdos por MemVOC")
    for word in menVOC_memories:
        new_word, created = Palabra.objects.get_or_create(nombre_palabra=word)
        words_memories[new_word.nombre_palabra] = new_word
        menVOC_memories_vocabulario.palabras.add(new_word)

    # Reduced memories by APJ
    apj_memories = ["infancia", "otoño", "invierno", "clima_caluroso",
                    "dolor", "hedor", "adiccion", "conflictos_personales"]
    apj_memories_vocabulario, created_apj_memories = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Memorias reducidas por APJ", descripcion="Lista reducida de memorias o recuerdos a partir de MemVOC por APJ segun 'USO DE TECNICAS MULTICRITERIO PARA LA OBTENCION DE UNA LISTA REDUCIDA DE EMOCIONES Y RECUERDOS PARA CONSUMIDORES DE CAFES ARTESANALES'")
    for word in apj_memories:
        new_word = words_memories[word]
        apj_memories_vocabulario.palabras.add(new_word)

    # Reduced memories by Toposis
    toposis_memories = ["amistad", "deporte", "vida", "obsequio", "verano",
                        "otoño", "clima_lluvioso", "clima_caluroso", "obesidad", "hedor"]
    toposis_memories_vocabulario, created_toposis_memories = Vocabulario.objects.get_or_create(
        nombre_vocabulario="Memorias reducidas por Toposis", descripcion="Lista reducida de memorias o recuerdos a partir de MemVOC por Toposis segun 'USO DE TECNICAS MULTICRITERIO PARA LA OBTENCION DE UNA LISTA REDUCIDA DE EMOCIONES Y RECUERDOS PARA CONSUMIDORES DE CAFES ARTESANALES'")
    for word in toposis_memories:
        new_word = words_memories[word]
        toposis_memories_vocabulario.palabras.add(new_word)


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0040_vocabulario_descripcion_and_more'),
    ]

    operations = [
        migrations.RunPython(create_words_emotions_memories),
    ]
