# Generated by Django 5.2.1 on 2026-02-16 15:00

from django.db import migrations


def create_styles_words(apps, schema_editor):
    EstiloPalabra = apps.get_model('tecnicas', 'EstiloPalabra')

    words_style = ["perfil flash", "sort", "napping", "vocabulario", "atributos"]

    for word in words_style:
        EstiloPalabra.objects.get_or_create(nombre_estilo=word)


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0041_auto_20260215_1546'),
    ]

    operations = [
        migrations.RunPython(create_styles_words),
    ]
