# Generated by Django 5.2.1 on 2026-03-03 19:38

from django.db import migrations

def create_tags_continue(apps, schema_editor):
    Etiqueta = apps.get_model('tecnicas', 'Etiqueta')

    create_tags = [
        {'valor_etiqueta': 'intensidad nula'},
        {'valor_etiqueta': 'intensidad moderada'},
        {'valor_etiqueta': 'intensidad fuerte'}
    ]

    for tag in create_tags:
        Etiqueta.objects.get_or_create(**tag)

class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0042_seeds_styles_words'),
    ]

    operations = [
        migrations.RunPython(create_tags_continue),
    ]
