from .autentication import autentication
from .login_catador import catadorLogin
from .main_panel import mainPanel
from .management_catadores import managementCatadores
from .panel_sessions import sesionesPanel
from .seleccion_tecnica import selecionTecnica
from .configuration_panel_basic import configuracionPanelBasic
from .configuration_panel_tags import configuracionPanelTags
from .configuration_panel_words import configurationsPanelWords
from .api_tag import newTag
from .catador_create import crearCatador