services:
  apache-web-test-sensorial:
    hostname: apache-web-test-sensorial
    container_name: apache-web-test-sensorial
    depends_on:
      - app-django-sensorial
    ports:
      - "7070:80"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.apache
    volumes:
        - ${SENSORIAL_BIND_BASE_PATH}/webapp:/var/www/html
        - ${SENSORIAL_BIND_BASE_PATH}/static:/var/www/static

  app-django-sensorial:
    hostname: app-django-sensorial
    container_name: app-django-sensorial
    build:
      context: .
      dockerfile: Dockerfile.django
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
        - ${SENSORIAL_BIND_BASE_PATH}/static:/app/static
    environment:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME_DATABASE=${DB_NAME_DATABASE}
        - STATIC_ROOT=${STATIC_ROOT}
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
        - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
