services: # Definicion de servicios. Se convertiran en contendores [Requerido]
  apache-web-test-sensorial:
    hostname: apache-web-test-sensorial
    container_name: apache-web-test-sensorial
    image: debian:12.1
    ports:
      - "7070:80"
    restart: unless-stopped
    command: # Ejecuta un comando específico dentro del contenedor, sobrescribiendo el comando por defecto de la imagen.
      - /bin/bash # Shell del sistema que ejecutara los comandos
      - -c # Significa que bash debe ejecutar la cadena como un comando
      - | # Separa una línea muy larga en múltiples lineas
        export DEBIAN_FRONTEND=noninteractive
        ln -snf /usr/share/zoneinfo/America/Mexico_City /etc/localtime && echo America/Mexico_City > /etc/timezone
        apt -y update
        apt install -y cron git apache2 iproute2 php php-{curl,zip,mysqli,xml,mbstring,gd,intl,soap}
        echo apache max_input_vars = 5000
        sed -i 's/^;max_input_vars *= *1000/max_input_vars = 5000/' /etc/php/8.2/apache2/php.ini
        service apache2 start
        tail -F keep-container.alive
    volumes: # Monta volúmenes para persistir o compartir datos entre el host y el contenedor. Las carpetas o archivos deben existir primero en el repositorio para mapearlos. Crear un index en la carpeta webapp para que el ejemplo funcione.
        - ${SENSORIAL_BIND_BASE_PATH}/webapp:/var/www/html # sintaxis ${SENSORIAL_BIND_BASE_PATH}/ruta_a_carpeta_o_archivo_en_el_repositorio:ruta_a_carpeta_o_archivo_en_el_contenedor