from .models_controller.tecnica_controller import TecnicaController
from .models_controller.escala_controller import EscalaController
from .models_controller.productos_controller import ProductosController
from .models_controller.ordenes_controller import OrdenesController
from .models_controller.palabras_controller import PalabrasController
from .models_controller.estilo_palabras_controller import EstiloPalabrasController
from .models_controller.palabras_controller import PalabrasController
from .models_controller.sesion_controller import SesionController
from .models_controller.calificacion_controller import CalificacionController
from .models_controller.catador_controller import CatadorController
from .models_controller.posicion_controller import PosicionController
from .models_controller.particiapacion_controller import ParticipacionController
from .models_controller.dato_controller import DatoController

from .views_controller.create_session.panel_basic_controller import PanelBasicController
from .views_controller.create_session.panel_tags_controller import PanelTagsController
from .views_controller.create_session.panel_codes_controller import PanelCodesController
from .views_controller.create_session.panel_words_controller import PanelWordsController
from .views_controller.create_session.panel_create_controller import PanelCreateController

from .views_controller.session_management.details_controller import DetallesController
from .views_controller.session_management.details_escala_controller import DetallesEscalasController
from .views_controller.session_management.details_rata_controller import DetallesRATAController
from .views_controller.session_management.details_cata_controller import DetallesCATAController
from .views_controller.session_management.details_pf_controller import DetallesPFController

from .views_controller.session_management.monitor_controller import MonitorController
from .views_controller.session_management.monitor_escalas_controller import MonitorEscalasController
from .views_controller.session_management.monitor_rata_controller import MonitorRATAController
from .views_controller.session_management.monitor_pf_controller import MonitorPFController

from .views_controller.sessions_tester.login_session_tester_controller import LoginSessionTesterController
from .views_controller.sessions_tester.list_sessions_tester_controller import ListSessionsTesterController

from .views_controller.sessions_tester.tests_forms.test_scales_controller import TestScalesController
from .views_controller.sessions_tester.tests_forms.test_rata_controller import TestRataController
from .views_controller.sessions_tester.tests_forms.test_cata_controller import TestCataController
from .views_controller.sessions_tester.tests_forms.test_pf_controller import TestPFController

from .views_controller.sessions_tester.init_session.init_session_escalas_controller import InitSessionEscalasController
from .views_controller.sessions_tester.init_session.init_session_rata_controller import InitSessionRATAController
from .views_controller.sessions_tester.init_session.init_session_pf_controller import InitSessionPFController

from .views_controller.vocabulary_manage.create_vocabulary_controller import CreateVocabularyController
from .views_controller.vocabulary_manage.list_vocabulary_controller import ListVocabularyController

from .api_controller.rating_sacales_controller import RatingScalesController
from .api_controller.rating_cata_controller import RatingCataController
from .api_controller.rating_pf_list_controller import RatingPFListController
from .views_controller.tester_list_controller import TesterListController
